spec_version: 1

outputs:
  url: sandbox  # can be sandbox, target

scripts:
  init.sh: |
    #!/bin/bash
    sudo pip3 install --upgrade pip
    sudo dnf install sqlite git -y
    sudo mkdir /var/www
    sudo mkdir /var/www/ddb
    sudo git clone https://github.com/kalsky/django-dashboard-black --depth 1 --branch=master /var/www/ddb
    cd /var/www/ddb
    echo "ALLOWED_HOSTS.append('*')" | sudo tee -a core/settings.py
    sudo sqlite3 db.sqlite3 "VACUUM;"
    sudo chmod 755 db.sqlite3
    sudo pip3 install -r requirements.txt
    sudo python3 manage.py collectstatic --noinput
    sudo python3 manage.py makemigrations
    sudo python3 manage.py migrate
    
  start.sh: |
    #!/bin/bash
    cd /var/www/ddb
    sudo python3 manage.py runserver 0.0.0.0:80

applications:
  ddb-app:
    spec_version: 1
    kind: application

    inputs:
      - PORT: 80
      - AZURE_VM_SIZE: Standard_B1s

    infrastructure:
      compute:
        spec:
          azure:
            vm_size: $AZURE_VM_SIZE

      # Port 80 will be opened externally to receive web requests
      connectivity:
        external:
          - web:
              port: $PORT

    # This is a clean Ubuntu server image that will be
    source:
      os_type: linux
      image:
        azure_image:
        - urn: cognosys:centos-8-2-free:centos-8-2-free:1.2019.0810
          username: adminuser

    configuration:
      initialization:
        script: init.sh
      # This command restarts the Apache server after the initialization completes
      start:
        script: start.sh
      # To validate the installation, we wait to see that the ports are available
      healthcheck:
        wait_for_ports: ALL
        timeout: 30

    debugging: 
      connection_protocol: SSH

blueprint:
  django-dashboard-black:
    spec_version: 1
    kind: blueprint
    metadata:
      description: >
        django dashboard black
    clouds: 
      - Azure: westus2

    applications:
      - ddb-app:
          input_values:
            - PORT: 80
            - AZURE_VM_SIZE: Standard_B1s

    debugging:
      availability: on